// Trilingual remedy content (deity, day, charity, fasting, lifestyle, gemstone).
// Mantra (Sanskrit + transliteration + count) stays language-neutral in
// data/remedies.ts. Consumed by the Remedies page and the reading engines.
import type { Lang } from './strings';
import type { PlanetId } from '../types/chart';

export interface RemedyC {
  deity: string; day: string; charity: string; fasting: string; lifestyle: string;
  gemstone: { stone: string; caution: string };
}

export const REMEDY_C: Record<Lang, Record<PlanetId, RemedyC>> = {
  en: {
    Sun: { deity: 'Sūrya / Lord Rāma', day: 'Sunday', charity: 'Wheat, jaggery, copper or red cloth to the needy on Sunday.', fasting: 'Sunday fast, one meal without salt.', lifestyle: 'Offer water to the rising Sun; honour your father and elders.', gemstone: { stone: 'Ruby', caution: 'Only if the Sun is a functional benefic and weak. Consult a qualified astrologer.' } },
    Moon: { deity: 'Chandra / Divine Mother', day: 'Monday', charity: 'Rice, milk, white cloth or silver on Monday.', fasting: 'Monday fast; devotion to Śiva/Pārvatī.', lifestyle: 'Honour and care for your mother; keep gentle emotional routines.', gemstone: { stone: 'Pearl', caution: 'Suits a weak but benefic Moon; avoid if afflicted or malefic for your Lagna.' } },
    Mars: { deity: 'Hanumān / Kārtikeya', day: 'Tuesday', charity: 'Red lentils, red cloth, or jaggery on Tuesday.', fasting: 'Tuesday fast; recite the Hanuman Chalisa.', lifestyle: 'Channel energy into discipline and exercise; practise patience.', gemstone: { stone: 'Red Coral', caution: 'Heating and powerful; only for a weak benefic Mars.' } },
    Mercury: { deity: 'Viṣṇu / Budha', day: 'Wednesday', charity: 'Green gram, green cloth, or books to students on Wednesday.', fasting: 'Wednesday observance; support education.', lifestyle: 'Practise clear, truthful speech; study and write.', gemstone: { stone: 'Emerald', caution: 'For a weak benefic Mercury; avoid if combust without guidance.' } },
    Jupiter: { deity: 'Bṛhaspati / Viṣṇu', day: 'Thursday', charity: 'Turmeric, chana dal, yellow cloth, or feeding teachers on Thursday.', fasting: 'Thursday fast with yellow food; respect teachers.', lifestyle: 'Seek wisdom, study scripture, act with generosity and ethics.', gemstone: { stone: 'Yellow Sapphire', caution: 'Generally benefic but still chart-dependent; verify Jupiter’s role first.' } },
    Venus: { deity: 'Śukra / Lakṣmī', day: 'Friday', charity: 'White sweets, curd, sugar, or white cloth on Friday.', fasting: 'Friday observance; honour women and the arts.', lifestyle: 'Cultivate beauty, harmony and balanced relationships.', gemstone: { stone: 'Diamond / White Sapphire', caution: 'Strong stone; only for a weak benefic Venus.' } },
    Saturn: { deity: 'Śani / Hanumān', day: 'Saturday', charity: 'Black sesame, mustard oil, iron, or black cloth to the poor on Saturday.', fasting: 'Saturday fast; serve the elderly and labourers.', lifestyle: 'Embrace discipline, honesty and service; avoid shortcuts.', gemstone: { stone: 'Blue Sapphire', caution: 'The most powerful and unpredictable stone; NEVER wear without careful testing.' } },
    Rahu: { deity: 'Durgā / Rāhu', day: 'Saturday', charity: 'Black/multicoloured cloth, mustard, coconut, or feeding the marginalised.', fasting: 'Observe Saturday; devotion to Durgā.', lifestyle: 'Cut through illusion; avoid obsession, gambling and shortcuts.', gemstone: { stone: 'Hessonite (Gomed)', caution: 'Only under expert guidance; can amplify obsession.' } },
    Ketu: { deity: 'Gaṇeśa / Ketu', day: 'Tuesday', charity: 'Multicoloured cloth, sesame, or feeding dogs and ascetics.', fasting: 'Devotion to Gaṇeśa; spiritual practice.', lifestyle: 'Cultivate detachment, meditation and letting go.', gemstone: { stone: 'Cat’s Eye', caution: 'Very subtle and sudden; only with expert guidance.' } },
  },
  hi: {
    Sun: { deity: 'सूर्य / श्रीराम', day: 'रविवार', charity: 'रविवार को गेहूँ, गुड़, तांबा या लाल वस्त्र जरूरतमंद को दें।', fasting: 'रविवार व्रत, बिना नमक का एक समय भोजन।', lifestyle: 'उगते सूर्य को जल अर्पित करें; पिता और बड़ों का सम्मान करें।', gemstone: { stone: 'माणिक्य', caution: 'केवल तब जब सूर्य कार्यात्मक शुभ और निर्बल हो। योग्य ज्योतिषी से परामर्श लें।' } },
    Moon: { deity: 'चंद्र / देवी माँ', day: 'सोमवार', charity: 'सोमवार को चावल, दूध, श्वेत वस्त्र या चांदी दान करें।', fasting: 'सोमवार व्रत; शिव/पार्वती की भक्ति।', lifestyle: 'माता का सम्मान और सेवा करें; कोमल भावनात्मक दिनचर्या रखें।', gemstone: { stone: 'मोती', caution: 'निर्बल किंतु शुभ चंद्र के लिए; पीड़ित या अशुभ हो तो टालें।' } },
    Mars: { deity: 'हनुमान / कार्तिकेय', day: 'मंगलवार', charity: 'मंगलवार को लाल मसूर, लाल वस्त्र या गुड़ दें।', fasting: 'मंगलवार व्रत; हनुमान चालीसा पाठ।', lifestyle: 'ऊर्जा को अनुशासन और व्यायाम में लगाएँ; धैर्य रखें।', gemstone: { stone: 'मूंगा', caution: 'तापकारी और प्रबल; केवल निर्बल शुभ मंगल के लिए।' } },
    Mercury: { deity: 'विष्णु / बुध', day: 'बुधवार', charity: 'बुधवार को मूंग, हरा वस्त्र या विद्यार्थियों को पुस्तकें दें।', fasting: 'बुधवार अनुष्ठान; शिक्षा को सहयोग दें।', lifestyle: 'स्पष्ट, सत्य वाणी बोलें; अध्ययन और लेखन करें।', gemstone: { stone: 'पन्ना', caution: 'निर्बल शुभ बुध के लिए; अस्त हो तो बिना मार्गदर्शन टालें।' } },
    Jupiter: { deity: 'बृहस्पति / विष्णु', day: 'गुरुवार', charity: 'गुरुवार को हल्दी, चना दाल, पीला वस्त्र या गुरुओं को भोजन दें।', fasting: 'गुरुवार पीले भोजन के साथ व्रत; गुरुओं का सम्मान।', lifestyle: 'ज्ञान खोजें, शास्त्र पढ़ें, उदारता और नैतिकता से कार्य करें।', gemstone: { stone: 'पुखराज', caution: 'सामान्यतः शुभ किंतु कुंडली पर निर्भर; गुरु की भूमिका पहले जाँचें।' } },
    Venus: { deity: 'शुक्र / लक्ष्मी', day: 'शुक्रवार', charity: 'शुक्रवार को श्वेत मिठाई, दही, शक्कर या श्वेत वस्त्र दें।', fasting: 'शुक्रवार अनुष्ठान; स्त्रियों और कलाओं का सम्मान।', lifestyle: 'सौंदर्य, समरसता और संतुलित संबंध विकसित करें।', gemstone: { stone: 'हीरा / श्वेत पुखराज', caution: 'प्रबल रत्न; केवल निर्बल शुभ शुक्र के लिए।' } },
    Saturn: { deity: 'शनि / हनुमान', day: 'शनिवार', charity: 'शनिवार को काला तिल, सरसों तेल, लोहा या काला वस्त्र गरीबों को दें।', fasting: 'शनिवार व्रत; वृद्धों और श्रमिकों की सेवा।', lifestyle: 'अनुशासन, ईमानदारी और सेवा अपनाएँ; शॉर्टकट से बचें।', gemstone: { stone: 'नीलम', caution: 'सबसे प्रबल और अप्रत्याशित रत्न; बिना सावधानीपूर्वक परीक्षण कभी न पहनें।' } },
    Rahu: { deity: 'दुर्गा / राहु', day: 'शनिवार', charity: 'काला/बहुरंगी वस्त्र, सरसों, नारियल, या वंचितों को भोजन।', fasting: 'शनिवार पालन; दुर्गा की भक्ति।', lifestyle: 'भ्रम को काटें; जुनून, जुआ और शॉर्टकट से बचें।', gemstone: { stone: 'गोमेद', caution: 'केवल विशेषज्ञ मार्गदर्शन में; जुनून बढ़ा सकता है।' } },
    Ketu: { deity: 'गणेश / केतु', day: 'मंगलवार', charity: 'बहुरंगी वस्त्र, तिल, या कुत्तों और साधुओं को भोजन।', fasting: 'गणेश की भक्ति; आध्यात्मिक साधना।', lifestyle: 'वैराग्य, ध्यान और त्याग विकसित करें।', gemstone: { stone: 'लहसुनिया', caution: 'बहुत सूक्ष्म और आकस्मिक; केवल विशेषज्ञ मार्गदर्शन में।' } },
  },
  ne: {
    Sun: { deity: 'सूर्य / श्रीराम', day: 'आइतबार', charity: 'आइतबार गहुँ, सख्खर, तामा वा रातो कपडा खाँचोमा परेकालाई दिनुहोस्।', fasting: 'आइतबार व्रत, नुनबिनाको एक छाक।', lifestyle: 'उदाउँदो सूर्यलाई जल अर्पण गर्नुहोस्; पिता र ठूलाबडाको सम्मान गर्नुहोस्।', gemstone: { stone: 'माणिक्य', caution: 'सूर्य कार्यात्मक शुभ र कमजोर भएमा मात्र। योग्य ज्योतिषीसँग परामर्श लिनुहोस्।' } },
    Moon: { deity: 'चन्द्र / देवी माता', day: 'सोमबार', charity: 'सोमबार चामल, दूध, सेतो कपडा वा चाँदी दान गर्नुहोस्।', fasting: 'सोमबार व्रत; शिव/पार्वतीको भक्ति।', lifestyle: 'आमाको सम्मान र सेवा गर्नुहोस्; कोमल भावनात्मक दिनचर्या राख्नुहोस्।', gemstone: { stone: 'मोती', caution: 'कमजोर तर शुभ चन्द्रका लागि; पीडित वा अशुभ भए नगर्नुहोस्।' } },
    Mars: { deity: 'हनुमान / कार्तिकेय', day: 'मंगलबार', charity: 'मंगलबार रातो मसुर, रातो कपडा वा सख्खर दिनुहोस्।', fasting: 'मंगलबार व्रत; हनुमान चालीसा पाठ।', lifestyle: 'ऊर्जालाई अनुशासन र व्यायाममा लगाउनुहोस्; धैर्य राख्नुहोस्।', gemstone: { stone: 'मुँगा', caution: 'तापकारी र प्रबल; कमजोर शुभ मंगलका लागि मात्र।' } },
    Mercury: { deity: 'विष्णु / बुध', day: 'बुधबार', charity: 'बुधबार मुँग, हरियो कपडा वा विद्यार्थीलाई पुस्तक दिनुहोस्।', fasting: 'बुधबार अनुष्ठान; शिक्षालाई सहयोग।', lifestyle: 'स्पष्ट, सत्य वाणी बोल्नुहोस्; अध्ययन र लेखन गर्नुहोस्।', gemstone: { stone: 'पन्ना', caution: 'कमजोर शुभ बुधका लागि; अस्त भए मार्गदर्शनबिना नगर्नुहोस्।' } },
    Jupiter: { deity: 'बृहस्पति / विष्णु', day: 'बिहीबार', charity: 'बिहीबार बेसार, चना दाल, पहेँलो कपडा वा गुरुलाई भोजन दिनुहोस्।', fasting: 'बिहीबार पहेँलो भोजनसहित व्रत; गुरुको सम्मान।', lifestyle: 'ज्ञान खोज्नुहोस्, शास्त्र पढ्नुहोस्, उदारता र नैतिकताले काम गर्नुहोस्।', gemstone: { stone: 'पुष्पराज', caution: 'सामान्यतः शुभ तर कुण्डलीमा निर्भर; गुरुको भूमिका पहिले जाँच्नुहोस्।' } },
    Venus: { deity: 'शुक्र / लक्ष्मी', day: 'शुक्रबार', charity: 'शुक्रबार सेतो मिठाई, दही, चिनी वा सेतो कपडा दिनुहोस्।', fasting: 'शुक्रबार अनुष्ठान; महिला र कलाको सम्मान।', lifestyle: 'सौन्दर्य, समरसता र सन्तुलित सम्बन्ध विकास गर्नुहोस्।', gemstone: { stone: 'हीरा / सेतो पुष्पराज', caution: 'प्रबल रत्न; कमजोर शुभ शुक्रका लागि मात्र।' } },
    Saturn: { deity: 'शनि / हनुमान', day: 'शनिबार', charity: 'शनिबार कालो तिल, तोरीको तेल, फलाम वा कालो कपडा गरिबलाई दिनुहोस्।', fasting: 'शनिबार व्रत; वृद्ध र श्रमिकको सेवा।', lifestyle: 'अनुशासन, इमानदारी र सेवा अपनाउनुहोस्; सर्टकटबाट बच्नुहोस्।', gemstone: { stone: 'नीलम', caution: 'सबैभन्दा प्रबल र अप्रत्याशित रत्न; सावधानीपूर्वक परीक्षणबिना कहिल्यै नलगाउनुहोस्।' } },
    Rahu: { deity: 'दुर्गा / राहु', day: 'शनिबार', charity: 'कालो/बहुरंगी कपडा, तोरी, नरिवल, वा वञ्चितलाई भोजन।', fasting: 'शनिबार पालना; दुर्गाको भक्ति।', lifestyle: 'भ्रमलाई काट्नुहोस्; जुनून, जुवा र सर्टकटबाट बच्नुहोस्।', gemstone: { stone: 'गोमेद', caution: 'विशेषज्ञ मार्गदर्शनमा मात्र; जुनून बढाउन सक्छ।' } },
    Ketu: { deity: 'गणेश / केतु', day: 'मंगलबार', charity: 'बहुरंगी कपडा, तिल, वा कुकुर र साधुलाई भोजन।', fasting: 'गणेशको भक्ति; आध्यात्मिक साधना।', lifestyle: 'वैराग्य, ध्यान र त्याग विकास गर्नुहोस्।', gemstone: { stone: 'लहसुनिया', caution: 'धेरै सूक्ष्म र आकस्मिक; विशेषज्ञ मार्गदर्शनमा मात्र।' } },
  },
};
